### ISSUE TITLE
Trusted device cannot be added

### ISSUE THREAD

**Issue by Seppl2202** [mkalioby/django-mfa2#30]
Hello,  
when adding a trusted device, I get the following error:
```
ERROR:django.request:Internal Server Error: /mfa/td/add
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/mfa/TrustedDevice.py", line 65, in add
uwsgi_1         |     trusted_keys=User_Keys.objects.filter(username=request.POST["username"],properties__has="$.key="+key)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
uwsgi_1         |     return self._filter_or_exclude(False, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
uwsgi_1         |     clone.query.add_q(Q(*args, **kwargs))
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
uwsgi_1         |     clause, _ = self._add_q(q_object, self.used_aliases)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
uwsgi_1         |     split_subq=split_subq, simple_col=simple_col,
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
uwsgi_1         |     condition = self.build_lookup(lookups, col, value)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1110, in build_lookup
uwsgi_1         |     lhs = self.try_transform(lhs, lookup_name)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1151, in try_transform
uwsgi_1         |     "permitted%s" % (name, output_field.__name__, suggestion)
uwsgi_1         | django.core.exceptions.FieldError: Unsupported lookup 'has' for JSONField or join on the field not permitted, perhaps you meant shas?
```

Has anyone else this error?
I am running in Docker and integrated django-mfa2 into DefectDojo

**Comment by mkalioby** [comment]
What is your database backend? and did you install 'jsonlookup'?

**Comment by Seppl2202** [comment]
Hi,
Backend is MySQL 5.7.32.
JsonLookup is installed (this is from inside the Docker container):
```
>>> import pkg_resources
>>> pkg_resources.get_distribution('jsonLookup').version
'0.9.0'
```
Python is 3.6.12

I dont see an import of JsonLookup in https://github.com/mkalioby/django-mfa2/blob/master/mfa/TrustedDevice.py, could that be the issue?

**Comment by Seppl2202** [comment]
Thanks for fixing, is this fix available via the pip package of django-mfa2?

**Comment by mkalioby** [comment]
Fixed in 2.0.5

**Comment by Seppl2202** [comment]
Thanks for the quick fix! Ill try this out

**Comment by Seppl2202** [comment]
Sorry to bother you:

```
from django.conf import settings
from jsonLookup import shasLookup
JSONField.register_lookup(shasLookup)
JSONField.register_lookup(hasLookup)
```
leading to: `NameError: name 'hasLookup' is not defined`

But the import of has_lookup in models.py is missing now :)
