### ISSUE TITLE
"ValueError: Invalid format string" at Email.py

### ISSUE THREAD

**Issue by hiroaki-kamo** [mkalioby/django-mfa2#4]
Hi there,

Thank you for making a great package.
I am doing MFA using Email.
"ValueError: Invalid format string" occurred when inputting OTP.

Occurrence is where "strftime ("% s ")" is described in Email auth.

----
Internal Server Error: /mfa/email/auth/
Traceback (most recent call last):
  File "C:\work\15.DEV\Anaconda3\envs\env-base\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\work\15.DEV\Anaconda3\envs\env-base\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\work\15.DEV\Anaconda3\envs\env-base\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\work\15.DEV\Anaconda3\envs\env-base\lib\site-packages\mfa\Email.py", line 47, in auth
    seconds = random.randint(settings.MFA_RECHECK_MIN, settings.MFA_RECHECK_MAX))).strftime("%s"))
ValueError: Invalid format string
----

%s > %S？

**Comment by mkalioby** [comment]
Thanks for stopping by

Can you please tell me which  version of Python & Django are you using?

**Comment by hiroaki-kamo** [comment]
thanks.

Django 2.1.7
Python 3.7

%s seems not to be supported on Windows.
It worked fine on Linux.
